import type { Metadata } from 'next'
import Nav from "./Nav/page";
import './globals.css'
import { Roboto } from "next/font/google";
import QueryWrapper from "../app/components/QueryWrapper";
import AddGamePresenter from './components/AddPresenter';

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto",
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`mx-4 md:mx-48 xl:mx-96 ${roboto.variable} bg-gray-200`}>
        
      <QueryWrapper>
          <Nav />
          {/* <AddGamePresenter/> */}
          {children}
        </QueryWrapper>
      </body>
    </html>
  );
}
